language: python

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      
install:
  - python setup.py install
  
script:
  - python -m test
